name: Auto Commit

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  Auto-Commit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Other steps that change files in the repository

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: SulthanTriesToCode
          commit_user_email: sulthanprabowo7@gmail.com

